// Composable dùng chung ngôn ngữ giữa các trang
// useState của Nuxt tự động chia sẻ state qua các component/page trong cùng session

export const useLang = () => useState<'ja' | 'en' | 'vi' | 'my'>('lang', () => 'ja')

export const i18nData = {
  ja: {
    title: "ラッキールーレット",
    won: "当選しました！",
    note: "コードごとに1回のみ抽選可能です。賞品の受け取りについては主催者にお問い合わせください。",
    spin: "回す",
    spinning: "回転中...",
    spin_now: "🎰 今すぐ回す",
    empty: "賞品が設定されていません。",
    congrats: "おめでとうございます！",
    close: "閉じる",
    out_of_prizes: "賞品がありません！",
    error: "エラーが発生しました。もう一度お試しください！",
    enter_new_code: "別のコードを入力",
    // access page
    access_title: "アクセスコードを入力",
    access_desc: "参加するには主催者からのコードを入力してください。",
    access_placeholder: "コードをここに入力...",
    access_btn: "続ける →",
    access_loading: "確認中...",
    access_error_default: "コードが無効です",
    start_btn: "スタート",
    promo_t1: "AU無制限WIFIに登録して",
    promo_t2: "iPhone 17 Pro Max を即ゲット",
  },
  vi: {
    title: "Vòng Quay May Mắn",
    won: "Bạn đã trúng giải!",
    note: "Mỗi mã chỉ được quay 1 lần. Liên hệ BTC để nhận giải.",
    spin: "QUAY",
    spinning: "Đang quay...",
    spin_now: "🎰 QUAY NGAY",
    empty: "Chưa có giải thưởng nào được cấu hình.",
    congrats: "Chúc mừng!",
    close: "Đóng",
    out_of_prizes: "Đã hết giải thưởng tặng kèm!",
    error: "Có lỗi xảy ra, vui lòng thử lại!",
    enter_new_code: "Nhập mã khác",
    // access page
    access_title: "Nhập mã tham gia",
    access_desc: "Vui lòng nhập mã tham gia do ban tổ chức cấp để quy đổi thưởng.",
    access_placeholder: "Nhập mã tại đây...",
    access_btn: "Tiếp tục →",
    access_loading: "Đang kiểm tra...",
    access_error_default: "Mã không hợp lệ",
    start_btn: "BẮT ĐẦU",
    promo_t1: "ĐĂNG KÝ WIFI AU KHÔNG GIỚI HẠN",
    promo_t2: "TRÚNG NGAY IPHONE 17 PRO MAX",
  },
  en: {
    title: "Lucky Spin Wheel",
    won: "You've won a prize!",
    note: "Each code can only be spun once. Contact the organizer to claim your prize.",
    spin: "SPIN",
    spinning: "Spinning...",
    spin_now: "🎰 SPIN NOW",
    empty: "No prizes have been configured.",
    congrats: "Congratulations!",
    close: "Close",
    out_of_prizes: "No prizes left!",
    error: "An error occurred, please try again!",
    enter_new_code: "Enter another code",
    // access page
    access_title: "Enter Participation Code",
    access_desc: "Please enter the participation code provided by the organizer to claim your reward.",
    access_placeholder: "Enter code here...",
    access_btn: "Continue →",
    access_loading: "Checking...",
    access_error_default: "Invalid code",
    start_btn: "START",
    promo_t1: "SIGN UP AU UNLIMITED WIFI",
    promo_t2: "WIN IPHONE 17 PRO MAX INSTANTLY",
  },
  my: {
    title: "ကံစမ်းမဲဘီး",
    won: "သင်ဆုရသွားပါပြီ!",
    note: "ကုဒ်တစ်ခုလျှင်တစ်ကြိမ်သာလှည့်နိုင်သည်။ ဆုထုတ်ယူရန် စီစဉ်သူအား ဆက်သွယ်ပါ။",
    spin: "လှည့်မည်",
    spinning: "လှည့်နေသည်...",
    spin_now: "🎰 ယခုလှည့်မည်",
    empty: "ဆုများကို သတ်မှတ်ထားခြင်းမရှိပါ။",
    congrats: "ဂုဏ်ယူပါတယ်!",
    close: "ပိတ်မည်",
    out_of_prizes: "ဆုများကုန်သွားပါပြီ!",
    error: "အမှားအယွင်းတစ်ခုဖြစ်ပွားခဲ့သည်၊ ကျေးဇူးပြု၍ ပြန်လည်ကြိုးစားပါ!",
    enter_new_code: "အခြားကုဒ်ရိုက်ထည့်ပါ",
    // access page
    access_title: "ပါဝင်ခွင့်ကုဒ်ရိုက်ထည့်ပါ",
    access_desc: "ဆုကိုရယူရန် စီစဉ်သူထံမှ ပေးသောပါဝင်ခွင့်ကုဒ်ကို ရိုက်ထည့်ပါ။",
    access_placeholder: "ကုဒ်ကို ဤနေရာတွင် ရိုက်ထည့်ပါ...",
    access_btn: "ဆက်လက်ဆောင်ရွက်မည် →",
    access_loading: "စစ်ဆေးနေသည်...",
    access_error_default: "ကုဒ်မမှန်ကန်ပါ",
    start_btn: "စတင်ရန်",
    promo_t1: "AU UNLIMITED WIFI စာရင်းသွင်းပြီး",
    promo_t2: "IPHONE 17 PRO MAX ချက်ချင်းရယူပါ",
  }
}

export const flags: Record<string, string> = {
  ja: '/nhat.png',
  en: '/anh.png',
  vi: '/viet.png',
  my: '/myanma.png'
}
